### ISSUE TITLE
No such file or directory.

### ISSUE THREAD

**Issue by style95** [major0/gh-comment-action#58]
Hello.
Thank you for the great action.

I am trying to use this action in my Github Enterprise and getting this error.

```
/home1/irteam/_work/_temp/d31d8bff-28de-4f79-a9ef-f3093e6fe3b9.sh: line 8: /home1/irteam/_work/_actions/dominic-kim/gh-comment-action/v1.0.1/gh-comment-action.sh: No such file or directory
Error: Process completed with exit code 1.
```

I manually synced this repo but could not make it.

Do you have any idea?

**Comment by major0** [comment]
This was a fumble on my-part, I had done some renaming of the scripts from the old `gh-issue-comment.sh` to `gh-comment-action.sh` and missed a whole slew of renames. Part of the problem is that, due to the nature of GitHub Actions, I am incapable of running some of the CI/CD Tests "from" the code contained w/in the pull-request (or at least I have not yet figured out a good way to do that). In short, the CI/CD tests passed because it was running the `link-artifact` tests from the `master` branch and not from the code-changes contained in the `pull-request`.

@style95 This should be fixed at this point if you want to give it another try. Please let me know if it isn't working as expected.
